### ISSUE TITLE
Windows position at start

### ISSUE THREAD

**Issue by Quax456** [ciribob/DCS-SimpleRadioStandalone#130] opened 2016-10-15 08:21 UTC
Hello,

I don't know if this was declared as a finding before?
Anytime I start SRS the main window is located on the upper left corner of my main monitor.
As explanation I do have a two monitor setup where my secondary is on the right.

This means I do always have to drag the window to the right.
The radio toggle window is working fine. Only the awacs radio window has the same behavior then the main setup window.

So my question is more like "Is it possible that SRS is recording the last windows positions and opens on this on next start?"

Regards

P.S: Or is it a Windows 10 issue? Maybe?

**Comment by birgersp** [comment] 2016-10-19 14:07
Duplicate of #125 ?

**Comment by ciribob** [comment] 2016-10-21 07:46
Yes duplicate of #125 

Window positioning is a bit of a minefield as if it ever goes wrong or you unplug a screen I need to handle it. Not impossible, just a bit fiddly...

I'll add to the list though for both those windows positions to be saved

**Comment by ciribob** [comment] 2016-10-22 21:17
Fixed in #136

**Closed by ciribob** 2016-10-22 21:17 UTC
Labels: accepted
