### ISSUE TITLE
Feature Request: Wider band for FC3 planes

### ISSUE THREAD

**Issue by szporwolik** [ciribob/DCS-SimpleRadioStandalone#259] opened 2018-07-02 19:18 UTC
With the "Extend" radio off it's not possible to set frequencies below 200MHz in some of the FC3 planes - in example F-15C . Please consider extending the band as most of the TWY/ATC in Caucascus are set around 150MHz.

**Comment by MorpheusXAUT** [comment] 2018-07-02 19:35
While DCS does not support any fully simulated radios for FC3 aircrafts, SRS still "upholds" limitations of the radios used by the aircraft in reality.

For the F-15, that appears to be the [AN/ARC-165](https://en.wikipedia.org/wiki/AN/ARC-164), which, according to available documentation, operates between 225.000 MHz and 399.975 MHz, the limits also applied by SRS.

Since the aircraft's radios would not be able to operate on lower frequencies if they were full-fidelity, all restrictions still apply for FC3 modules (as far as they're public knowledge).

**Comment by MorpheusXAUT** [comment] 2018-07-15 17:36
Closing issue as this is intended behavior.
Feel free to re-open it if required!

**Closed by MorpheusXAUT** 2018-07-15 17:36 UTC
