### ISSUE TITLE
Mic Passthrough even when NO PASSTHROUGH is selected

### ISSUE THREAD

**Issue by dlwalter** [ciribob/DCS-SimpleRadioStandalone#255] opened 2018-06-18 15:37 UTC
I'm having an issue where I still hear my voice with ~0.5 second delay in my headphones even when I select NO MIC PASSTHROUGH in the dropdown.  I have a workaround where I assign both audio output and mic passthrough to another set of speakers, test the audio, then assign the audio output to my headphones and select Connect to Server to "lock" in my selection.  If I select audio preview before connecting to the server the mic passthrough will occur on whatever audio output device is selected (in this case my headphones).

**Comment by MorpheusXAUT** [comment] 2018-06-18 16:41
Just to confirm: the issue also occurs when you simply connect to the SRS server without previewing your audio, correct?
Another user reported a simular "feedback" issue a few days ago, but it would only appear in the audio preview for him, but was gone (both for him and people listening to him) when he connected to a server.

I'll try to reproduce it using your provided steps (launch SRS, start audio preview, stop audio preview, connect to server). There might be an issue with "unsetting" the audio preview, leading to the unintended mic passthrough.

**Comment by dlwalter** [comment] 2018-06-18 18:08
I'll have to double check, but I am pretty sure I get the mic passthrough
when connecting directly without previewing.

**Comment by ciribob** [comment] 2018-06-19 09:55
Are you sure you don't have two instances of SRS open? 

Check your tray to make sure.

To be absolutely sure, make sure to restart PC, open SRS, make sure the right drop-down says no pass through, and hit connect.

**Comment by MorpheusXAUT** [comment] 2018-06-22 15:55
Wasn't able to reproduce this issue locally unfortunately, no matter what combination of mic/output/preview selections I tried 😕 
Any update on whether this also happens if you connect straight away like ciribob described?

**Comment by dlwalter** [comment] 2018-06-22 16:18
Sorry, haven't had time to check due to work.  This weekend I should have
an opportunity.

**Comment by dlwalter** [comment] 2018-06-24 03:47
Connecting straight to the server without previewing audio works fine. Looks like it only happens when I preview the audio.

**Comment by ciribob** [comment] 2018-06-24 18:15
You have to turn off preview audio after use, by clicking it again :)

Connecting doesnt automatically stop preview audio, though it will in the next release

**Comment by dlwalter** [comment] 2018-06-24 19:51
I was getting the passthrough even after turning off the preview audio.

**Comment by ciribob** [comment] 2018-06-25 20:21
im not able to replicate unless I dont turn off preview audio - i'd double check you're doing that before connecting?

**Comment by MorpheusXAUT** [comment] 2018-06-28 17:06
@dlwalter could you try the new `beta` release (available [here](https://github.com/ciribob/DCS-SimpleRadioStandalone/releases/tag/1.5.3.1) ) if you have time (install it to a separate folder and run the `stable` installer again to make sure all scripts are correct if you want to uninstall the `beta`) and see if you still encouter the issue?

While I didn't find anything in specific that could cause this, I've added extra steps to make sure the audio preview and mic are set up properly when connecting to a server. Would be curious is you still encouter it with this version.

If you don't want to use the `beta`, you could try it out in about 2 weeks when the `beta` gets released as a `stable` version.

**Comment by ciribob** [comment] 2018-07-15 08:43
If preview audio is left on  - it'll be turned off in the new release

**Closed by ciribob** 2018-07-15 08:43 UTC
