### ISSUE TITLE
F-14 Intercom Delay

### ISSUE THREAD

**Issue by triplecs1** [ciribob/DCS-SimpleRadioStandalone#413] opened 2020-02-18 02:29 UTC
In reference to the previous posting closed on Nov 2, 2019, pilot and I have had this issue since release 1.7.3.0.  Currently, we're both on 1.7.5.0., and have experienced a delay of ~15-20 seconds between tx/rx on the ICS, and it seems no change is noted with the use of hot mic or cold mic.  Use of -159/-182 radios is unaffected, and works as advertised.

**Comment by ciribob** [comment] 2020-02-18 08:27
As a first test, disable the hot mic for 39 seconds

Then enable hot mic and start talking - is there a delay?

**Comment by triplecs1** [comment] 2020-02-21 23:58
Ciribob,

Sorry for the late response, work, kids. etc...

Pilot and I tested as requested, no improvement noted.

**Comment by ciribob** [comment] 2020-02-22 09:38
I'm unable to replicate, are you able to try on a different server and send a recording?

Is the ptt sound on transmitting also delayed?

Do you get the same delay if you don't use hotmic?

**Comment by ciribob** [comment] 2020-03-29 17:14
Closing for now due to lack of reply

**Comment by rstoki** [comment] 2020-04-08 00:49
I can confirm that the problem with latency is still there in version 1.7.7.0. The latency builds over time -- at the start, the latency is negligible (not noticable), but after a while (30-40 minutes?) it can be as high as 10 seconds. 

Is there any way how I can help with tracking this problem down? I'm experienced with C# programming, maybe I can 'hack' it on my side to dump some logs, recordings etc. when it occurs during the play.

**Comment by ciribob** [comment] 2020-04-08 06:42
Please try disabling the hot mic if the latency increases noticeable for around 3l60 seconds, and then enable hot mic again

Does that clear the latency?

**Comment by rstoki** [comment] 2020-04-09 09:57
We will test it in more exact way, however the preliminary tests with "disabling hot mic for 60 seconds" seemed not to lower the latency.  It is faster to perform quick reconnect (i.e., Disconnect && Connect) which helps -- but this needs to be done by both Pilot and RIO (reconnect of only one party lowers the delay by some amount, but not completely). 

This ticket seems to address the same issue as in #328 -- maybe only one of these tickets should stay opened to avoid confusion?  (probably this one as it is related to newer SRS version)

**Comment by rstoki** [comment] 2020-04-21 10:50
Well, I ave to admit, that sometimes it seems, that switching to Cold Mic for some time without transmission **may help** lowering the latency back to normal. I was not able to find the exact pattern.  

Should we test it in more exact way?  Will it help to address the problem?

**Comment by ciribob** [comment] 2020-04-25 14:04
Please try this BETA here: https://github.com/ciribob/DCS-SimpleRadioStandalone/releases/tag/1.8.0.0

Might solve the issue entirely but you'll all have to be running this version

**Comment by ciribob** [comment] 2020-05-01 18:13
Please test in the latest 1.8.0.1 release

**Closed** 2020-05-02 19:20 UTC

**Comment by rstoki** [comment] 2020-05-02 23:30
> Please test in the latest 1.8.0.1 release

Thanks, we will try and report back.
