### ISSUE TITLE
Intense Stutter When Multiple Radios Receive

### ISSUE THREAD

**Issue by Peliia** [ciribob/DCS-SimpleRadioStandalone#512] opened 2020-12-27 19:54 UTC
Flying the F-14 in the RIO seat, whenever fore and aft radios were both receiving, the audio would intensely stutter, as if rapidly flickering between the two voices. Intercom worked fine behind all that as long as the radios were turned down in volume. Pilot heard this as well.

Played F-14 RIO on the 132nd vWing server with around 12 other clients, OB build 59398, SRS v. 1.9.3.0
PC Specs:
i7-3770
GTX 1060 3 GB
24 GB RAM
Game and system on SATA SSD
100 Mbit DSL Internet, no NAT

**Comment by ciribob** [comment] 2020-12-28 09:00
Are you able to get a recording for me?

**Comment by Peliia** [comment] 2020-12-28 16:43
Yes. Done on the PGAW server with the help of a kind fellow pilot and the Overlord Bot.
https://cdn.discordapp.com/attachments/292244530374246400/793157189383487528/Radio_flicker.ogg

**Comment by ciribob** [comment] 2020-12-29 08:54
Can you replicate this consistently and would you be up for trying a test version as I cant reproduce it?

If you join the SRS discord and message me there, I'll get you a build tonight

**Comment by ciribob** [comment] 2021-01-02 08:32
Fixed in #513 - release shortly

**Closed by ciribob** 2021-01-02 08:32 UTC
